site_name: Cookie Service for Angular
site_description: Angular service for interacting with the HTTP cookies, implemented in TypeScript.
site_author: Cédric Belin - cedric@belin.io
site_url: https://docs.belin.io/ngx-cookies

docs_dir: ../doc
site_dir: ../www

repo_name: git.belin.io
repo_url: https://git.belin.io/cedx/ngx-cookies
edit_uri: ''

copyright: Copyright &copy; 2016 - 2020 Cédric Belin
extra:
  social:
    - icon: fontawesome/solid/globe
      link: 'https://belin.io'
    - icon: fontawesome/brands/github
      link: 'https://github.com/cedx'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/cedxbelin'
    - icon: fontawesome/brands/linkedin
      link: 'https://linkedin.com/in/cedxbelin'

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true

nav:
  - Overview: index.md
  - Installation: installation.md
  - Usage:
      - Programming interface: usage/api.md
      - Cookie options: usage/options.md
      - Iteration: usage/iteration.md
      - Events: usage/events.md
  - About:
      - License: about/license.md
      - See also: about/see_also.md

theme:
  favicon: img/favicon.ico
  features:
    - instant
  icon:
    logo: fontawesome/solid/book-reader
    repo: fontawesome/brands/git-alt
  name: material
  palette:
    accent: red
    primary: blue
